language: node_js
node_js:
  - "6.9.1"
cache:
  directories:
    - node_modules # NPM packages
install:
  - npm install
script:
  - npm run docs:build

deploy:
  provider: pages
  target-branch: master # Necessary for organisation github pages.
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: source

branches:
  only:
    - source

notifications:
  email: false
